In [13]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
  

def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)
        
def select_blah_blah(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT (m1.firstname || ' ' || m1.surname) AS first_last_name, (m2.firstname || ' ' || m1.surname) AS member_who_recommended
        FROM Members AS m1
        LEFT JOIN Members AS m2
        ON m1.memid = m2.recommendedby
        ORDER BY first_last_name ASC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"

    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
        select_blah_blah(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)
('Anna Mackenzie', None)
('Anne Baker', None)
('Burton Tracy', 'Ponder Tracy')
('Charles Owen', None)
('Darren Smith', 'Janice Smith')
('Darren Smith', 'Gerald Smith')
('Darren Smith', 'Charles Smith')
('Darren Smith', 'Jack Smith')
('Darren Smith', 'Anna Smith')
('Darren Smith', None)
('David Farrell', None)
('David Jones', 'Douglas Jones')
('David Pinker', None)
('Douglas Jones', None)
('Erica Crumpet', None)
('Florence Bader', 'Ramnaresh Bader')
('GUEST GUEST', None)
('Gerald Butters', 'Matthew Butters')
('Henrietta Rumney', None)
('Henry Worthington-Smyth', None)
('Hyacinth Tupperware', None)
('Jack Smith', None)
('Janice Joplette', 'Nancy Joplette')
('Janice Joplette', 'David Joplette')
('Jemima Farrell', 'Timothy Farrell')
('Jemima Farrell', 'David Farrell')
('Joan Coplin', None)
('John Hunt', None)
('Matthew Genting', 'Henrietta Genting')
('Millicent Purview', 'John Purview')
('Nancy Dare', None)
('Ponder Stibbons', 'Anne Stibbons')
('Ponder Stibbons', 'Florence Stibbons')
('Ramnaresh Sarwin', None)
('Tim Boothe', None)
('Tim Rownam', 'Tim Rownam')
('Timothy Baker', 'Joan Baker')
('Tracy Smith', 'Henry Smith')
('Tracy Smith', 'Millicent Smith')
('Tracy Smith', 'Erica Smith')

In [10]:
#question 11
def select_blah_blah(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
         SELECT (m1.firstname || ' ' || m1.surname) AS first_last_name, (m2.firstname || ' ' || m1.surname) AS member_who_recommended
        FROM Members AS m1
        LEFT JOIN Members AS m2
        ON m1.memid = m2.recommendedby
        ORDER BY first_last_name ASC;
 """
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

In [ ]:
#question 10
def select_question_10(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT name, SUM(facility_revenue) AS total_facility_revenue FROM (SELECT name, CASE WHEN memid = 0 THEN guestcost * slots ELSE membercost * slots END AS facility_revenue FROM Bookings as b JOIN Facilities as f USING (facid)) AS sub GROUP BY name ORDER BY total_facility_revenue LIMIT 3;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

In [ ]:
#question 12
def select_question_12(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT facid, COUNT(memid) 
       FROM Bookings
    WHERE memid !=0
    GROUP BY facid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

In [ ]:
#question 13
def select_question_13(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT sub.months, COUNT(sub.memid) 
       FROM (SELECT MONTH( starttime ) AS months, memid FROM Bookings WHERE memid !=0) AS sub GROUP BY sub.months;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)